title: Linda Nguyen — UX Research Portfolio
theme: jekyll-theme-cayman
description: Lead-level UX Researcher specializing in product strategy, enterprise workflows, and growth experimentation.
markdown: kramdown
github:
  is_project_page: false

